# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee87388ef4cc869304a7aa91a1c5abba65c1aacd94bde0a7acd50bc5d41d430afe891651b9524f5f89e36cee0157014d113cca31f927a01ca031bb8da83cd3fa

test:
  secret_key_base: c87561045ba67f160458b538697484e9084f5d2007c6b184c563c9a584a993cbfd553d6d22dbbf52c095699bd570a086c749cab7c4e94187a0efec63593c6b9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
